# AI Summary: GitHub Actions workflow that automatically updates README.md when repository files change.
# Triggers on pushes to main branch (excluding README.md changes) and allows manual triggering.
# Sets up Python, runs the update_readme.py script, and commits changes back to the repository.

name: Update README

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Run update_readme.py
      run: python private/update_readme.py
      
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code README.md || echo "::set-output name=modified::true"
      continue-on-error: true
        
    - name: Commit changes if README.md was modified
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git commit -m "Auto-update README.md with latest publications"
        
    - name: Push changes
      if: steps.git-check.outputs.modified == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
