# AI Summary: GitHub Actions workflow that automatically updates README.md and full paper files when repository files change.
# Triggers on pushes to main branch (excluding README.md changes) and allows manual triggering.
# Sets up Python, runs the update_readme.py script, and commits changes back to the repository.

name: Update README and Generate Full Papers

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Run create_full_papers.py
      run: python private/create_full_papers.py
      
    - name: Run update_readme.py
      run: python private/update_readme.py
      
    - name: Check for changes
      id: git-check
      run: |
        # Check for README.md changes
        git diff --exit-code README.md || echo "readme_modified=true" >> $GITHUB_OUTPUT
        
        # Check for new full paper files
        FULL_PAPERS=$(git ls-files --others --exclude-standard | grep "_full.md" || echo "")
        if [ -n "$FULL_PAPERS" ]; then
          echo "full_papers_exist=true" >> $GITHUB_OUTPUT
          echo "Found untracked full papers: $FULL_PAPERS"
        fi
        
        # Set the overall modified flag if either README or full papers changed
        if [ -n "$(git diff --name-only README.md)" ] || [ -n "$FULL_PAPERS" ]; then
          echo "modified=true" >> $GITHUB_OUTPUT
        fi
        
        # Show status for debugging
        git status
      continue-on-error: true
        
    - name: Commit changes if files were modified or created
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Always try to add README.md
        git add README.md || echo "No changes to README.md to commit"
        
        # Only add full papers if they exist
        if [ "${{ steps.git-check.outputs.full_papers_exist }}" == "true" ]; then
          # Find all untracked full paper files and add them individually
          git ls-files --others --exclude-standard | grep "_full.md" | xargs git add || echo "No full papers to add"
          echo "Added full paper files to commit"
        fi
        
        # Commit if there are changes to be committed
        if ! git diff --staged --quiet; then
          git commit -m "Auto-update README.md and generated full papers"
          echo "Changes committed successfully"
        else
          echo "No changes to commit"
          exit 1
        fi
        
    - name: Push changes
      if: steps.git-check.outputs.modified == 'true' && success()
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
